Repository cloud-bulldozer/benchmark-wrapper, pull requests merged in 2020-08, with the labels that each got.

#187 Avoid rebuilding operator and checking ES twice
  .gitignore
  ci/common.sh
  ci/run_ci.sh
  src/fio_wrapper/ci_test.sh
  src/fs_drift_wrapper/ci_test.sh
  src/hammerdb/ci_test.sh
  src/iperf/ci_test.sh
  src/pgbench_wrapper/ci_test.sh
  src/smallfile_wrapper/ci_test.sh
  src/sysbench/ci_test.sh
  src/uperf_wrapper/ci_test.sh
  src/vegeta_wrapper/ci_test.sh
  src/ycsb_wrapper/ci_test.sh
Labels: CI, ok to test

#200 Disable native CPU detection
  src/fio_wrapper/Dockerfile
Labels: bug, ok to test

#202 Fixing the FIPS problem
  src/run_snafu.py
Labels: ok to test

#196 Drop cache
  src/run_snafu.py
  src/utils/request_cache_drop.py
Labels: ok to test

#173 Add get prometheus data to run snafu
  requirements.txt
  setup.cfg
  src/fio_wrapper/Dockerfile
  src/fs_drift_wrapper/Dockerfile
  src/hammerdb/Dockerfile
  src/linpack_wrapper/Dockerfile
  src/pgbench_wrapper/Dockerfile
  src/run_snafu.py
  src/smallfile_wrapper/Dockerfile
  src/uperf_wrapper/trigger_uperf.py
  src/utils/get_prometheus_data.py
  src/utils/prometheus_labels/all_labels.json
  src/utils/prometheus_labels/included_labels.json
  src/utils/py_es_bulk.py
  src/ycsb_wrapper/Dockerfile
Labels: ok to test

#203 extensions for mysql and postgresql added
  ci/run_ci.sh
  snafu/hammerdb/Dockerfile
  snafu/hammerdb/hammerdb_wrapper.py
  snafu/hammerdb/trigger_hammerdb.py
Labels: ok to test

#204 Add -f flag to prune
  ci/run_ci.sh
Labels: CI, bug, ok to test
