Repository cloud-bulldozer/benchmark-wrapper, pull requests merged in 2021-08, with the labels that each got.

#307 Change linpack URL to latest Intel bits, change LINPACK_DAT so no need to be root
  snafu/linpack_wrapper/Dockerfile
  snafu/linpack_wrapper/linpack.sh
Labels: ok to test

#311 Downgrade elasticsearch-py version due to incompatibility issues
  ci/common.sh
  setup.cfg
Labels: bug, ok to test

#306 Add Unit and Documentation Build Tests
  .coveragerc
  .github/workflows/doc.yaml
  .github/workflows/unit.yaml
  .gitignore
  MANIFEST.in
  docs/source/conf.py
  docs/source/contributing.md
  docs/source/contributing/adding_workloads.ipynb
  docs/source/contributing/unit_testing.md
  setup.cfg
  snafu/benchmarks/uperf/uperf.py
  snafu/config.py
  snafu/process.py
  tests/unit/test_config.py
  tests/unit/test_process.py
  tox.ini
Labels: ok to test

#312 Remove unused podman push
  ci/common.sh
Labels: bug, ok to test, CI

#291 add support for rosa machinepools on scale wrapper
  setup.cfg
  snafu/scale_openshift_wrapper/Dockerfile
  snafu/scale_openshift_wrapper/scale_openshift_wrapper.py
  snafu/scale_openshift_wrapper/trigger_scale.py
Labels: ok to test

#317 Revamp pre-commit CI
  .flake8
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .pylintrc
  docs/source/conf.py
  snafu/benchmarks/__init__.py
  snafu/benchmarks/_benchmark.py
  snafu/benchmarks/_load_benchmarks.py
  snafu/benchmarks/uperf/uperf.py
  snafu/registry.py
  tests/unit/test_process.py
Labels: ok to test

#335 Update pre-commit Config
  .pre-commit-config.yaml
  snafu/benchmarks/_benchmark.py
  snafu/benchmarks/uperf/uperf.py
  snafu/config.py
  snafu/registry.py
Labels: ok to test
